### ISSUE TITLE
Contribute with the localization

### ISSUE THREAD

**Issue by coyoterj** [TryGhost/Dawn#11]
I would like to contribute with localization, of course, if it is of interest to you

Thanks!

**Comment by coyoterj** [comment]
Hi,
Localization pt-br is done. Other languages remain to be updated:
ar.json
bg.json
de-informal.json
de.json
en.json
es.json
fa.json
fr-informal.json
fr.json
he.json
id.json
it.json
ky.json
lt.json
nl.json
pl.json
pt.json
ro.json
ru.json
tr.json
vi.json
zh-hans.json
zh-hant.json
[Dawn-master.zip](https://github.com/TryGhost/Dawn/files/5610098/Dawn-master.zip)

**Comment by minimaluminium** [comment]
Hey @coyoterj, thanks for your support! However, we're keeping our official themes free of translation helpers and localization files in terms of simplicity. You can always add localization to your site on your end.
