### ISSUE TITLE
Navigation more menu 

### ISSUE THREAD

**Issue by f0x2501** [TryGhost/Dawn#12]
Hi'
I don't understand how can I configure the navigation menu to have the three dots menu '...' like in your demo site.
If I enter 12 menu items they're all displayed on the same line.
Do I miss something ?
Best Regards

PS great theme thank you very much !

**Comment by minimaluminium** [comment]
Hey @f0x2501, the theme looks for a menu item with three dots `...` in its URL and chooses the item as a toggle. Then the menu items after this will be added to the sub-menu automatically. Here is how it's configured in the theme's demo.

![Screen Shot 2020-12-03 at 10 47 13 AM](https://user-images.githubusercontent.com/1418797/100957198-fe01fc00-3554-11eb-8fe7-7c1f4da40091.png)

**Comment by f0x2501** [comment]
Thank you so much for this so useful answer.
