### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by Fourenn** [TryGhost/Dawn#15]
Hello.
When I searched contents in Korean, it doesn't work.
It seems that only English title and contents can be searched now.
How can I solve this?

Thank you.

**Comment by amanv8060** [comment]
@Fourenn how are you generating api key ?
i need help

**Comment by ever-blogger** [comment]
I have similar issue too, it doesn't work on Chinese title too.

**Comment by minimaluminium** [comment]
Hey @Fourenn and @ever-blogger! We used Elasticlunr.js for indexing the posts, and by default, the library supports only English. [Here](https://github.com/weixsong/lunr-languages) is a repo for elasticlunr.js language support. And [here](https://github.com/weixsong/elasticlunr.js/issues/22#issuecomment-245564338) is a helpful comment from the maintainer for integrating different language than English in the library.

The code in the theme that initializes elasticlunr can be found [here](https://github.com/TryGhost/Dawn/blob/aa87b7ad09c40246710f4885ffd07021ff722e19/assets/js/main.js#L362) where you can add the changes advised by the library maintainer.
