### ISSUE TITLE
Cannot change `posts_per_page`

### ISSUE THREAD

**Issue by tobalsan** [TryGhost/Dawn#16]
Hi there,

I changed the config value of `posts_per_page` in the `package.json` file of the theme, but it has no effect.
Is this the correct way to change the number of posts displayed on the homepage?

Thanks for this great theme.

**Comment by tobalsan** [comment]
Nevermind, the change seems to have taken effect only after I changed another parameter then ran `ghost restart`.

**Comment by minimaluminium** [comment]
Hey @tobalsan, thanks for getting back with your solution 🙂
