### ISSUE TITLE
Superfluous </symbol>

### ISSUE THREAD

**Issue by AlexanderZeilmann** [TryGhost/Dawn#18]
The line
https://github.com/TryGhost/Dawn/blob/82e4d7b5bd255bdabc5d171cd41f68e36719eacc/partials/icons.hbs#L44
should be removed, as the ```<symbol>``` is already closed one line earlier.

**Comment by minimaluminium** [comment]
Hey @AlexanderZeilmann, thanks for that. Fixed the issue in 4eb37d0.
