### ISSUE TITLE
How to make post content wider?

### ISSUE THREAD

**Issue by akuzni2** [TryGhost/Dawn#20]
I'm very new to Html/CSS and haven't found any documentation online on editing the CSS files to make the post's content wider. Is there any way someone can tell me how to do that?

**Comment by minimaluminium** [comment]
Hey 👋  We ask that you please do not use GitHub for support or feature requests 😄. We use GitHub solely for bug-tracking and on-going feature development.

Our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!
