### ISSUE TITLE
Is there a way to change the way the newsletter format? If yes, which file needs to change?

### ISSUE THREAD

**Issue by devika7** [TryGhost/Dawn#24]

**Comment by minimaluminium** [comment]
Hey 👋 . We ask that you please do not use GitHub for support or feature requests 😄. We use GitHub solely for bug-tracking and on-going feature development.

Our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!
