### ISSUE TITLE
Easy Way To Disable Light/Dark/System Theme Changing (Pick Static Default)

### ISSUE THREAD

**Issue by logangreer** [TryGhost/Dawn#25]
I'd love to disable the theme changing in Dawn, but can't figure out how. Is there a simple way to set the default and let it always be that way? I've tried deleting the head code, and the footer choices, but realize that the theme still defaults to whichever mode the OS is on. Not sure where to edit/change this behavior.

If this behavior isn't easily editable, I'd love to see it be a value that can be easily changed somehow in a future update to this excellent theme.

**Comment by minimaluminium** [comment]
Hey @logangreer, you can disable the theme switching by adding a bit of code in `Code injection > Site Header`.

```html
<script>
    localStorage.setItem('dawn_theme', 'light');
</script>

<style>
    .menu-item.js-theme {
        display: none;
    }
</style>
```

The first part of the code will force the light theme, and the latter one hides the theme toggle on the footer. On the other hand, if you want to keep the dark theme, make sure to replace `light` with `dark`.

**Comment by logangreer** [comment]
Thanks!
