### ISSUE TITLE
Can't yarn dev and yarn zip "Error: [object Object] is not a PostCSS plugin"

### ISSUE THREAD

**Issue by jamochl** [TryGhost/Dawn#27]
Hi guys, love the theme. I can't seem to yarn dev or yarn zip due to an apparent PostCSS error

Tested this using a fresh git clone and following the instructions. On Arch Linux, have gulp, nodejs and yarn install globally.

yarn worked fine

![image](https://user-images.githubusercontent.com/58202195/104674362-a223b900-5737-11eb-9529-e15d1acdb7d3.png)

But for both yarn dev and yarn zip have this error

![image](https://user-images.githubusercontent.com/58202195/104674421-bd8ec400-5737-11eb-9c93-1ffcc21d25ae.png)

Help would be appreciated!

**Comment by minimaluminium** [comment]
Hey @jamochl, thanks for your report! Just pushed a fix in https://github.com/TryGhost/Dawn/commit/f55a35cce04dcd930aad3e168d743fe8b66b7880. Make sure you run `yarn install` after pulling the latest version.

**Comment by jamochl** [comment]
It works @minimaluminium , thanks for the quick response! This is my first time using ghost and the like, and i'm new to many of these css pre-processors and workflows. It is great to not have to worry about this for several days and contemplate changing themes. Legendary dude.
