### ISSUE TITLE
Wider Code Blocks

### ISSUE THREAD

**Issue by frakman1** [TryGhost/Dawn#31]
I love this theme. My only concern is that the code block is far too narrow. So is the post content to be honest but it's more acute with the code blocks.

Here is an example:

![image](https://user-images.githubusercontent.com/5826484/105627752-b2f2bf80-5e06-11eb-8e1d-ffed06ed85e2.png)

I tracked it down to this .kg-canvas class in the kg.css file. 

Changing the value of 640 within `min(640px, calc(100% - 8vw))` works within the inspector live-view. ~~However when I change the actual file in the theme folder and restart ghost, it reverts to 640 again.~~ Apparently, something was cached and I saw the change once the cache was cleared.

I'm not very CSS/HTML savvy so I'm sure I am missing a basic web development concept here

Could you please point me to where I would need to go in order to change the width of code blocks and posts in general?

I am using the prism syntax highlighter with standard site header and site footer code injections.

This is the code block I am looking at and changing line 136 in particular
https://github.com/TryGhost/Dawn/blob/fdb1ee25303290f265969f020075f61172006c3d/assets/css/misc/kg.css#L128-L154

**Comment by mvolpato** [comment]
Hi @frakman1 
You can try to add custom css for the `<pre>` tag:
```
grid-column: wide-start/wide-end;
```

<img width="1125" alt="Screenshot 2021-01-25 at 20 32 21" src="https://user-images.githubusercontent.com/7138011/105756195-93fe4580-5f4c-11eb-9055-7df99a65bb9c.png">

You can try that by going to your admin panel: **Settings** - **Code injection**, and then add this to the **Site Header** field:

```
<style>
    pre {
        grid-column: wide-start/wide-end;
	}
</style>
```

You can even be more specific by using a better css selector

```
<style>
    .single-content > pre {
        grid-column: wide-start/wide-end;
	}
</style>
```

I am also not an expert on HTML/CSS, so let me know if this worked for you.

**Comment by frakman1** [comment]
Thank you. That seems to work. 
I don't understand where you see `.single-content > pre` I looked through the inspect fields but didn't see it.

**Comment by minimaluminium** [comment]
Yeah, @mvolpato's solution is the most straightforward way to make the code blocks or any other element inside the post content wider. Dawn has 3 grid columns, main (640px), wide (920px) and full (full width), and you can use them like:

```css
grid-column: wide-start/wide-end;

/* Or */

grid-column: full-start/full-end;
```

**Comment by d0u9** [comment]
> Yeah, @mvolpato's solution is the most straightforward way to make the code blocks or any other element inside the post content wider. Dawn has 3 grid columns, main (640px), wide (920px) and full (full width), and you can use them like:
> 
> ```css
> grid-column: wide-start/wide-end;
> 
> /* Or */
> 
> grid-column: full-start/full-end;
> ```

I have added the CSS style in my site header injection but seems nothing has been changed since that.

By the way, is that possible to make the whole post area wider? for browsing pages on a large-size screen, the margins left and right waste too much space.
