### ISSUE TITLE
Feature request: Be able to disable all member related functionality

### ISSUE THREAD

**Issue by Jorijn** [TryGhost/Dawn#35]
I'm a simple person; I like writing some content, sharing my thoughts, and publishing them for the world to see. For that, I'm using the Dawn theme.

With the recent v4.0.0 release, it looks like member-related CTA buttons are forced upon us.

Please make it so that we can disable it if we want.

For people with the same issue, there's a temporary workaround, you can inject custom CSS into your header:

```html
<style>
    header.site-header .header-right button, section.single-cta, .cover-cta {
        display: none;
    }
</style>
```

**Comment by minimaluminium** [comment]
Hey @Jorijn 👋

If you have a feature request/suggestion, use our forum's [Ideas category](https://forum.ghost.org/c/ideas/5)

We ask that you please do not use GitHub for support or feature requests 😄. We use GitHub solely for bug-tracking and on-going feature development.

Our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!

**Comment by d0u9** [comment]
These two buttons can still be found in the mobile web in the drop-down menu top-right corner after applying @Jorijn 's code snippet.
