### ISSUE TITLE
The accent color isn't used

### ISSUE THREAD

**Issue by Hoosier3** [TryGhost/Dawn#37]
I just upgraded to version 4 and while reinstalling the theme, the accent color did not come with the new theme. Although, I do see it here https://github.com/TryGhost/Dawn/blob/b69eee50ee8fb1fda5f4234bd95bed47e2ca12ba/assets/css/general/basics.css

New users may want the orange accent color they see in the demo. So, I thought I should post this.

**Comment by minimaluminium** [comment]
The theme uses publication's default accent color set in `Settings > Branding` which was introduced in Ghost v4. If you want to use the orange accent color as on the demo, you can set it `#ff572f` in the branding settings :)
