### ISSUE TITLE
OwlCarousel is not a function error in the console

### ISSUE THREAD

**Issue by Timothep** [TryGhost/Dawn#40]
I loaded the theme into the admin interface of my Ghost installation, and I'm getting the following error:

```
jquery-3.5.1.min.js:2 Uncaught TypeError: $(...).owlCarousel is not a function
    at featured (main.js:129)
    at HTMLDocument.<anonymous> (main.js:15)
    at e (jquery-3.5.1.min.js:2)
    at t (jquery-3.5.1.min.js:2)
```

The featured posts are then not displayed. The `<div class="featured-feed owl">` has a CSS property of `display:none;`

I'm not sure where to search next. And hint? Thanks!

**Comment by minimaluminium** [comment]
Hey @Timothep, it looks like you're using `main.js` which is a development file that doesn't include 3rd party libraries (including OwlCarousel). We use `main.min.js` which is a bundle of all the JS as defined [here](https://github.com/TryGhost/Dawn/blob/639c1de073cea3dd399545d5719be7d7510bfa57/default.hbs#L55). Could you check again?

**Comment by Timothep** [comment]
Hi @minimaluminium, thanks for the answer. 

Somehow, it has to do with the Blog-import function. I have a ghost pro hosted blog. I want to try Ghost4.0 locally before upgrading. Checking if my theme isn't broken etc.

I exported the 3.x blog and loaded it locally in 4.x. That's probably the problem. Before the import, the featured posts work fine. Afterwards it is screwed.

I thought I would get only the posts through the export, but somehow, some Settings are coming with it.

If I upgrade my hosten Blog, I expect the export to work, but I won't be able to test the theme first 😅

Tim

**Comment by minimaluminium** [comment]
👋  hello again,

Hmm, I doubt this error has something to do with import process. It looks like the error comes from the theme itself. Would you be able to download your theme from the admin, and share the link with me?

**Comment by Timothep** [comment]
Hi @minimaluminium, I finally found the problem
 I was injecting an older version of JQuery via the "Code Injection" settings.
