### ISSUE TITLE
Some requests~

### ISSUE THREAD

**Issue by akimolll** [TryGhost/Dawn#42]
![before](https://user-images.githubusercontent.com/1827701/121776895-e2da0e00-cbc1-11eb-80e7-85771e76d97f.jpg)
before
![after](https://user-images.githubusercontent.com/1827701/121776902-ea99b280-cbc1-11eb-82ed-e8d05bbb2edc.jpg)
after

Hi, excuse me.
I'm officially in the arms of ghost.

At the same time, I fell in love with this theme, not only because it's free, I think it fits the usage habits of many people.
But here I want to make a detailed adjustment, I am a layman, so I come to ask questions.

1 How can I put the search icon further to the right? It looks like the picture will be more balanced. Sorry, I turned off login~~
2 How to define the size of the icon? I found that it was a little big on the screen of the mobile phone and wanted to reduce it.

Thanks again for such a great theme, I can't help installing it.

**Comment by akimolll** [comment]
![3252](https://user-images.githubusercontent.com/1827701/121778716-be366400-cbca-11eb-970a-8bd7010e27b7.jpg)

I kept the login style on the right side, so it looks much better.
I noticed that it can only display 5 articles. How can I set more articles by default?

**Comment by akimolll** [comment]
![4545](https://user-images.githubusercontent.com/1827701/121779681-6d753a00-cbcf-11eb-9191-e6d5b584b505.jpg)
In addition, how can I set the width of the article?

**Comment by akimolll** [comment]
![235235](https://user-images.githubusercontent.com/1827701/121798222-b2dd4a00-cc57-11eb-818f-e9c3bb697fa2.jpg)
![RDYDFHFD](https://user-images.githubusercontent.com/1827701/121798223-b53fa400-cc57-11eb-87d5-31e09b588284.jpg)
Is this a bit wider than the default theme?

**Comment by minimaluminium** [comment]
Hey 👋 . We ask that you please do not use GitHub for support or feature requests 😄. We use GitHub solely for bug-tracking and on-going feature development.

Our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!
