### ISSUE TITLE
Margins on Microsoft Edge (Mobile) disappear

### ISSUE THREAD

**Issue by dietrichai** [TryGhost/Dawn#43]
Some default themes I have tried are exhibiting weird behavior on Edge Mobile browser (I use Android). For some reason the margins disappear on this particular browser. It occurs on several themes, including Dawn (see screenshots), Casper, and Edition which I've also tried. This also happens on Pages. Also notice that the portal button gets affected as well.

Edge Browser
![Screenshot_20210622_133234_com microsoft emmx](https://user-images.githubusercontent.com/86342823/123101940-1db42f80-d467-11eb-923b-744fffa9a841.jpg)

Chrome
![Screenshot_20210622_133314_com android chrome](https://user-images.githubusercontent.com/86342823/123101968-2442a700-d467-11eb-825d-8ce9d1cd2bae.jpg)

**Comment by minimaluminium** [comment]
Hey @dietrichai,

Which version of Edge are you using? I've just tested your site on Edge (mobile) 46.3.23 and it works without any issue.

![IMG_86E078D56C05-2](https://user-images.githubusercontent.com/1418797/123194076-753eb380-d4d8-11eb-820d-0b78efbda386.jpeg)

**Comment by dietrichai** [comment]
Hi @minimaluminium !

I'm using 46.05.24 which is the latest one available on Google Play. Are you using iOS? I think the issue might be limited to Android. I've tested it on several android devices (another mobile phone and a tablet) and the results are the same:

![Screenshot_20210624-112105_Edge](https://user-images.githubusercontent.com/86342823/123198269-61e31680-d4df-11eb-9fdd-f28c5d7c9a58.jpg)

**Comment by dietrichai** [comment]
@minimaluminium 

Similar thing happens on other themes like Casper and Edition just looking at their demo sites. Should I post this on respective threads?

Casper
![Screenshot_20210625_094129_com microsoft emmx](https://user-images.githubusercontent.com/86342823/123356472-60c2ef80-d59a-11eb-9150-8ad0a2662a21.jpg)

Edition
![Screenshot_20210625_094203_com microsoft emmx](https://user-images.githubusercontent.com/86342823/123356529-7506ec80-d59a-11eb-8287-2dcbfcd44c32.jpg)

For Edition there appears to be additional space/margin on the right beyond the actual layout.

**Comment by minimaluminium** [comment]
@dietrichai Yes, I'm using Edge on iOS. It looks like the Android version doesn't support CSS Grid. Its [browser support](https://caniuse.com/css-grid) is pretty great, and we're not planning to ditch it. So I don't think it should be listed as theme issues, but rather should be reported to the browser side.
