### ISSUE TITLE
Fatal error when uploading the theme to Ghost

### ISSUE THREAD

**Issue by AlDjuric** [TryGhost/Dawn#47]
I get the following error. I checked default.hbs and found where "match" is used, but can't quite figure out what the problem is with it
_______
Fatal error:  Templates must contain valid Handlebars
Oops! You seemed to have used invalid Handlebars syntax. This mostly happens, when you use a helper that is not supported.
See the full list of available helpers here.

Affected files:
default.hbs: Missing helper: "match"

**Comment by AlDjuric** [comment]
Seems to only affect https://mindspun.io/ and not ghost.io

**Comment by minimaluminium** [comment]
Hey @AlDjuric,

`{{#match}}` helper support was added in Ghost 4.19.0, and the custom theme settings support was added in 4.20.0. Make sure you're using the latest version of Ghost to get the new features working on your site.
