### ISSUE TITLE
Login and Subscribe modals are not working

### ISSUE THREAD

**Issue by Michael-Brooks** [TryGhost/Dawn#5]
I have just downloaded and installed the Dawn theme and have managed to get search working. However, the login and subscribe modals don't appear to be showing. I uploaded the routes file, tried clearing cache and seeing if there were any instruction I missed.  [My blog is here](https://blog.michaelbrooks.dev).

**Comment by Michael-Brooks** [comment]
Thank you, that is exactly where I heard the news. I think the writing on the latest blog post could be changed. I know you probably have no control, but maybe someone at Ghost could be notified.

>All IVEEL themes are optimised to work with upcoming Ghost memberships and subscriptions functionality.
>
>At present this requires some code knowledge, however in the next few weeks we'll be launching some changes that will mean all of these themes will work automatically with members/subscriptions without any code required.

It made me think that I would be able to implement it myself by using the Readme on this repo, but if that's not the case then I will wait until the update comes. Thanks again.

**Comment by dkh215** [comment]
> At present this requires some code knowledge

@minimaluminium Are there any docs on what code we can add ourselves in the meantime?

**Comment by minimaluminium** [comment]
@dkh215 You can get started by exploring the Members doc [here](https://ghost.org/docs/members/introduction/). The section "Theme Development" is the one you might be interested. 

Also if you need some detailed code example, you can check out [Lyra theme](https://github.com/TryGhost/Lyra). More specifically:

- [Forms and account page](https://github.com/TryGhost/Lyra/tree/master/members)
- [Notifications](https://github.com/TryGhost/Lyra/blob/master/partials/notifications.hbs)
- [Members related scripts](https://github.com/TryGhost/Lyra/blob/master/default.hbs#L76-L150)
- [Custom routing](https://github.com/TryGhost/Lyra/blob/master/routes.yaml)

**Comment by Qoraiche** [comment]
Waiting for this too!

**Comment by EspressoFarmer** [comment]
Why on earth was the theme not properly updated once membership was removed? In the marketing blog post it says this theme is for newsletter authors. Now we are meant to wait? There was no notice in the theme instructions, the links were left in... this is poor form on Ghost's part. Our team has wasted hours customizing this theme only to discover the key thing we need - working membership out of the box, has been pulled without notice. 

We are not seasoned devs, we are designers. If your response is that we should have looked at the code base, you may have a serious misunderstanding of part of your user base. 

Can you provide the previous theme files with membership already working?

**Comment by matthanley** [comment]
✨ As [previously mentioned](https://github.com/TryGhost/Dawn/issues/5#issuecomment-712719568) Portal is now publicly available as of [Ghost 3.37](https://github.com/TryGhost/Ghost/releases/).

**Comment by edgarasben** [comment]
Updated to Ghost 3.38.3, Portal UI is available in admin interface, but the buttons on the website still does not work. Did anyone got this working?

**Comment by minimaluminium** [comment]
Hey @edgarasben, any error in the console? Is there any live link where I can take a look at?

**Comment by edgarasben** [comment]
@minimaluminium I had some issues with setting up email first (Mailgun) but now it's fixed and free memberships are available. Paid buttons still does not work, but I think it's because I have to connect to Stripe first and test mode does not work without. So I will have to try when I have time and report about this later.
