### ISSUE TITLE
Help with formatting issues when embedding gists?

### ISSUE THREAD

**Issue by braimee** [TryGhost/Dawn#51]
Hello,

Love this theme, and use it on my 7 Minute Security podcast site: https://7ms.us.  However, on several of my pages, such as [https://7ms.us/webinars/](https://7ms.us/webinars/), I embed Github gists, and when I do the formatting gets messed up and I have to highlight text to actually see it:

![gists](https://user-images.githubusercontent.com/17596787/148845384-eb2daf6c-2224-4727-880c-3b6af13106d3.png)

Is there some CSS, etc. I can use to fix this formatting issue?

Thanks,
Brian

**Comment by minimaluminium** [comment]
Hello @braimee,

For some reason, the titles in the gist is inheriting the theme title colors. When the theme is in dark mode, the title colors turn into white and it's invisible on white background.

The easiest fix would be adding explicit color to titles inside the gist. For example,

```css
.gist :is(h1, h2, h3, h4, h5, h6) {
    color: #1a1a1a;
}
```

**Comment by braimee** [comment]
@minimaluminium thanks for the advice!  Sorry for the newb question but would you mind providing a bit more direction on where to stick this code?  I read articles like [this one](https://codersblock.com/blog/customizing-github-gists/) and am thinking there are some `import` statements I need to make at the top of the gist, but not sure which ones.

**Comment by minimaluminium** [comment]
@braimee I'm not very familiar with customizing gist, but you can simply insert the CSS in `Settings > Code injection > Site Header` in your Ghost admin. It should be wrapped in `<style>` tag.

```html
<style>
    .gist :is(h1, h2, h3, h4, h5, h6) {
        color: #1a1a1a;
    }
</style>
```

**Comment by braimee** [comment]
That worked thank you!
