### ISSUE TITLE
Can posts be configured to show *all* tags?

### ISSUE THREAD

**Issue by braimee** [TryGhost/Dawn#53]
Hi again :-).  I noticed that each post seems to only show one of its associated tags.  For example, this [podcast episode](https://7ms.us/7ms-499-desperately-seeking-a-super-siem-for-smbs-part-6/) about SIEM solutions shows *podcast* as a tag, but you can also find it under the [tag for *siem*](https://7ms.us/tag/siem/).  

Can I make a config change so that posts show *all* tags?

**Comment by minimaluminium** [comment]
Hey 👋 . We ask that you please do not use GitHub for support or feature requests 😄. We use GitHub solely for bug-tracking and on-going feature development.

Our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!
