### ISSUE TITLE
Lacales translation doesn´t work

### ISSUE THREAD

**Issue by manox-myth** [TryGhost/Dawn#54]
Hello. I made a folder called "locales" and added my hu.json translation file, bud Dawn doesn´t switch from English. What can be the problem?

**Comment by minimaluminium** [comment]
Hey @manox-myth, make sure you use the translation helper `{{t}}` for the strings you want to translate in the theme code. More info: https://ghost.org/docs/themes/helpers/translate/

**Comment by manox-myth** [comment]
Thanks for your reply, I´ve read the article. Sorry for being ignorant, but which files contain the strings? I´ve checked other themes like WorldCasper2 where I did find the strings for translation.

**Comment by minimaluminium** [comment]
Let's say you want to translate the text "Subscribe now" of the button on the homepage. [The text](https://github.com/TryGhost/Dawn/blob/1f4b4bb8196cd2a9f9bc7006e05b1f217e24f851/partials/cover.hbs#L15) can be found in `partials/cover.hbs` file. You can also do a global search for the text you want to translate to find them quickly.

Our official themes don't include any translation helpers for the simplicity. 

We ask that you please do not use GitHub for support or feature requests 😄. We use GitHub solely for bug-tracking and on-going feature development.

Our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!
