### ISSUE TITLE
About search function

### ISSUE THREAD

**Issue by tungdh1** [TryGhost/Dawn#58]
I can't use the Search function, even though I injection this code in header, is it not enabled or has it changed?

<script>
     var gh_search_key = 'this is my content-api';
     var gh_search_migration = 'v2';
</script>

**Comment by minimaluminium** [comment]
Hey @tungdh1, the theme now uses a custom theme setting for the content API key. You can find the instructions on the [about page](https://dawn.ghost.io/about/) of the theme demo.
