### ISSUE TITLE
Can't `yarn dev`

### ISSUE THREAD

**Issue by edonyzpc** [TryGhost/Dawn#66]
According to the document, to build Dawn of `main` branch, do `yarn` then `yarn dev` but it emits the following error:

```bash
root@ubuntu-focal:~/code/Dawn#
>> yarn dev
yarn run v1.22.19
error Command "dev" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It should be the `package.json` to be blamed, and it seems this file is not updated.

**Comment by minimaluminium** [comment]
Hey @edonyzpc, should be fixed now.
