### ISSUE TITLE
Dropdown Menu?

### ISSUE THREAD

**Issue by cphpi** [TryGhost/Dawn#68]
Halo! i downloaded and use this theme as well but when i tried to create dropdown menu is's not work?!
I try see the demo site it's show ... for dropdown
any tutorial can teach?
thx

**Comment by minimaluminium** [comment]
Hey @cphpi, the dropdown is automatically created when there are more than 5 menu items. More on https://dawn.ghost.io/about/

**Comment by cphpi** [comment]
ok can i setup to more than 4 menu items?

**Comment by minimaluminium** [comment]
The only way at the moment would be making changes in the main JS file and rebuild the assets with `yarn build`. First change [this](https://github.com/TryGhost/Dawn/blob/6081287c50d47beacd4e4e529cf90a933eb13aca/assets/js/main.js#L26) to 4, and then change [this](https://github.com/TryGhost/Dawn/blob/6081287c50d47beacd4e4e529cf90a933eb13aca/assets/js/main.js#L27) to 3.
