### ISSUE TITLE
Media Queries missing for header search button?

### ISSUE THREAD

**Issue by nicholasareed** [TryGhost/Dawn#69]
When I run `yarn zip` the resulting output doesn't include any media queries for the `.gh-search` button in the header. 

This results in the button always showing twice, instead of being hidden.

**Comment by nicholasareed** [comment]
Well, I tracked it down to the @tryghost/shared-theme-assets dependency, but couldn't sort out why it wasnt using the media query that was added lately [https://github.com/TryGhost/Themes/commits/main/themes/_shared/assets/css/components/header.css#L82](https://github.com/TryGhost/Themes/blob/main/themes/_shared/assets/css/components/header.css#L82)

To get it working for myself, I just added the following to my `assets/css/site/header.css` 

```
@media (max-width: 991px) {
    .gh-head-actions .gh-search {
        display: none;
    }
}

@media (min-width: 992px) {
    .gh-head-brand .gh-search {
        display: none;
    }
}
```

**Comment by minimaluminium** [comment]
Hey @nicholasareed, you're correct! The issue was the version of `@tryghost/shared-theme-assets` dependency haven't been updated. Could you pull the latest update, run `yarn` again and see if it works?

**Comment by nicholasareed** [comment]
Works for me now, thanks!
