### ISSUE TITLE
Upgrade button non-functional

### ISSUE THREAD

**Issue by nickyvanurk** [TryGhost/Dawn#8]
When I log in on the demo website and press the then appearing upgrade button top right screen in the navigation I get to see a modal saying:

Choose your plan
[Continue]

That's it. That doesn't seem right. I remember the original theme (before it got bought by Ghost) had a selection of 3 pricing options. It seems to be missing here. When I press the continue button, which now doesn't make sense, I get to see an error: "Failed to process checkout, please try again".

Would love to hear what is going wrong here.

Cheers.

**Comment by minimaluminium** [comment]
Hey Nicky! The old membership flow was deprecated by Portal - Ghost's new feature added in 3.37.0. The incomplete upgrade plan UI was related with the demo site, it wasn't connected to Stripe. It's now connected to Stripe and the upgrade popup looks like this.

![Screen Shot 2020-11-06 at 6 47 38 PM](https://user-images.githubusercontent.com/1418797/98358038-11f33480-2061-11eb-99f5-168e9bc2ca4d.png)
