### ISSUE TITLE
Subscribe and Login buttons don't work

### ISSUE THREAD

**Issue by MrTehes** [TryGhost/Dawn#9]
Hi there,

I've just tried the Dawn theme.
I have downloaded the .zip and upload it on my website, but it seems that the "Subscribe" and "logins" buttons don't show the popup.

I tried to upload the routes.yaml form the theme folder but nothing seems to work.
I also don't find where the .hbs files with the popup are in the theme folder. 

Thanks

**Comment by johlym** [comment]
If this post: https://ghost.org/changelog/iveel/ is to be believed, the theme still needs a little work to be done. Specifically, it's missing the http://github.com/TryGhost/Portal reference that generates the popup. I would be adding the code yourself would take care of it, but can't say for sure.

**Comment by minimaluminium** [comment]
Hey @MrTehes, the membership flow of the theme is powered by Portal - Ghost's [new feature](https://ghost.org/changelog/portal/) added in 3.37.0. If it's not working, it's most likely you haven't updated your Ghost instance yet. You don't need any custom code or routing.

**Comment by MrTehes** [comment]
Oh thanks ! My bad... I didn't see the changelog and the Portal feature. Everything works fine now.
